### ISSUE TITLE
Timed out while checking status of Gcc Disk

### ISSUE THREAD

**Issue by u39kun** [sequenceiq/docker-cloudbreak#16]
Attempted to create a cluster.
Cloudbreak ended up creating sequence_debian image and the network, but it failed to perform the rest:

01:51:20.302 [threadPoolExecutor-7] INFO  c.s.c.s.PollingService - Polling attempt 59.
01:51:20.303 [threadPoolExecutor-7] INFO  c.s.c.s.s.c.g.GccDiskCheckerStatus - Checking status of Gcc Disk 'gcedockertest-0' on '51' stack.
01:51:25.629 [threadPoolExecutor-7] INFO  c.s.c.r.RetryingStackUpdater - Updated stack resources: [stack: '51', status: '{}', statusReason: '{}'].
01:51:25.629 [threadPoolExecutor-7] ERROR c.s.c.s.s.f.ProvisionContext - Unhandled exception occured while creating stack.
com.sequenceiq.cloudbreak.controller.BuildStackFailureException: Something went wrong. Instances in Gcc clouddisk 'gcedockertest-0' not started in a reasonable timeframe on '51' stack.
	at com.sequenceiq.cloudbreak.service.stack.connector.gcc.GccProvisioner.buildStack(GccProvisioner.java:92) ~[cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.flow.ProvisionContext.buildStack(ProvisionContext.java:60) ~[cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionSetupCompleteHandler.accept(ProvisionSetupCompleteHandler.java:30) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionSetupCompleteHandler.accept(ProvisionSetupCompleteHandler.java:16) [cloudbreak.jar!/:na]
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:74) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.invokeConsumer(ConsumerFilteringEventRouter.java:101) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:66) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.BaseDispatcher$Task.execute(BaseDispatcher.java:109) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.ThreadPoolExecutorDispatcher$ThreadPoolTask.run(ThreadPoolExecutorDispatcher.java:108) [reactor-core-1.0.1.RELEASE.jar!/:na]

**Comment by doktoric** [comment]
I closing this issue because it is very outdated.
We are using now centos any this problem was fixed.
