### ISSUE TITLE
cloudbreak running locally off docker; azure deployment fails

### ISSUE THREAD

**Issue by paul-lupu** [sequenceiq/docker-cloudbreak#22]
Hello, 

Running on Ubuntu 14.04 LTS with sudo for everything: 

What i've done:
- started a docker daemon locally with #sudo docker -d &
- checked ports are open and available from host machine running the docker containers
- created an azure credential + uploaded the cert file to Management Certs on azure
- created a basic template, like the one showed in this video: https://www.youtube.com/watch?v=E6bnEW76H_E 
- pressed Create and Run cluster. 

The problem: 
- deploy completely fails, i ocasionally get a storage account created in my azure with a name like: 1b87e6504a48ca801eastus2
- there is nothing showing inside the interface, after I do a hard refresh I get a: "Internal server error occured while setting up provisioning."

The output log is bellow: 
keyStorePath=file:///tmp/50.jks
2015-02-13 08:15:36,426 [http-nio-8080-exec-5] create:145 INFO  c.s.c.s.s.DefaultStackService - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:CREDENTIAL] [id:50] [name:lupugeorgepaul] Publishing PROVISION_REQUEST event [StackId: '50']
2015-02-13 08:15:36,465 [thread-pool-executor-dispatcher-3] accept:37 INFO  c.s.c.s.s.h.ProvisionRequestHandler - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Accepted PROVISION_REQUEST event.
keyStorePath=file:///tmp/50.jks
2015-02-13 08:15:36,608 [http-nio-8080-exec-8] create:90 INFO  c.s.c.s.c.AmbariClusterService - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Cluster requested [BlueprintId: 50]
2015-02-13 08:15:36,666 [http-nio-8080-exec-8] doUpdateStackCluster:280 INFO  c.s.c.r.RetryingStackUpdater - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:CLUSTER] [id:2] [name:plupusandbox] Saved cluster '2' for stack.
2015-02-13 08:15:36,667 [http-nio-8080-exec-8] create:103 INFO  c.s.c.s.c.AmbariClusterService - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:CLUSTER] [id:2] [name:plupusandbox] Publishing CLUSTER_REQUESTED event
2015-02-13 08:15:36,668 [thread-pool-executor-dispatcher-4] accept:30 INFO  c.s.c.s.c.h.ClusterRequestHandler - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Accepted CLUSTER_REQUESTED event.
2015-02-13 08:15:36,669 [thread-pool-executor-dispatcher-4] accept:41 INFO  c.s.c.s.c.h.ClusterRequestHandler - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Cluster install requested but the stack is not completed yet. Installation will start after the stack is ready.
[Fatal Error] :1:1: Content is not allowed in prolog.
2015-02-13 08:15:41,447 [thread-pool-executor-dispatcher-3] handleResponse:494 WARN  g.n.h.RESTClient - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Error parsing 'application/xml' response
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:147) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:200) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.ParserRegistry.parseXML(ParserRegistry.java:267) ~[http-builder-0.7.1.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:952) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:411) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:427) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:560) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:489) ~[http-builder-0.7.1.jar!/:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) [httpclient-4.3.jar!/:4.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) [httpclient-4.3.jar!/:4.3]
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient.put(RESTClient.java:163) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient$put.call(Unknown Source) [http-builder-0.7.1.jar!/:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) [groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) [groovy-all-2.1.8.jar!/:2.1.8]
	at com.sequenceiq.cloud.azure.client.AzureClientUtil.createBlobContainer(AzureClientUtil.groovy:39) [azure-rest-client-0.1.18.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.connector.azure.AzureProvisionSetup.createBlobContainer(AzureProvisionSetup.java:149) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.connector.azure.AzureProvisionSetup.setupProvisioning(AzureProvisionSetup.java:98) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.flow.ProvisionSetupContext.setupProvisioning(ProvisionSetupContext.java:42) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:38) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:19) [cloudbreak.jar!/:na]
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:74) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.invokeConsumer(ConsumerFilteringEventRouter.java:101) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:66) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.BaseDispatcher$Task.execute(BaseDispatcher.java:109) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.ThreadPoolExecutorDispatcher$ThreadPoolTask.run(ThreadPoolExecutorDispatcher.java:108) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
[Fatal Error] :1:1: Content is not allowed in prolog.
2015-02-13 08:15:42,185 [thread-pool-executor-dispatcher-3] handleResponse:494 WARN  g.n.h.RESTClient - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Error parsing 'application/xml' response
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:147) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:200) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.ParserRegistry.parseXML(ParserRegistry.java:267) ~[http-builder-0.7.1.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:952) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:411) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:427) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:560) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:489) ~[http-builder-0.7.1.jar!/:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) [httpclient-4.3.jar!/:4.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) [httpclient-4.3.jar!/:4.3]
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient.put(RESTClient.java:163) [http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient$put.call(Unknown Source) [http-builder-0.7.1.jar!/:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) [groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) [groovy-all-2.1.8.jar!/:2.1.8]
	at com.sequenceiq.cloud.azure.client.AzureClientUtil.copyOsImage(AzureClientUtil.groovy:71) [azure-rest-client-0.1.18.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.connector.azure.AzureProvisionSetup.setupProvisioning(AzureProvisionSetup.java:99) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.flow.ProvisionSetupContext.setupProvisioning(ProvisionSetupContext.java:42) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:38) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:19) [cloudbreak.jar!/:na]
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:74) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.invokeConsumer(ConsumerFilteringEventRouter.java:101) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:66) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.BaseDispatcher$Task.execute(BaseDispatcher.java:109) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.ThreadPoolExecutorDispatcher$ThreadPoolTask.run(ThreadPoolExecutorDispatcher.java:108) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
2015-02-13 08:15:42,197 [thread-pool-executor-dispatcher-3] setupProvisioning:44 ERROR c.s.c.s.s.f.ProvisionSetupContext - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Unhandled exception occured while setting up provisioning.
groovyx.net.http.ResponseParseException: The specified blob does not exist.
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:495) ~[http-builder-0.7.1.jar!/:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[httpclient-4.3.jar!/:4.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.jar!/:4.3]
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515) ~[http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient.put(RESTClient.java:163) ~[http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.RESTClient$put.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at com.sequenceiq.cloud.azure.client.AzureClientUtil.copyOsImage(AzureClientUtil.groovy:71) ~[azure-rest-client-0.1.18.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.connector.azure.AzureProvisionSetup.setupProvisioning(AzureProvisionSetup.java:99) ~[cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.flow.ProvisionSetupContext.setupProvisioning(ProvisionSetupContext.java:42) ~[cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:38) [cloudbreak.jar!/:na]
	at com.sequenceiq.cloudbreak.service.stack.handler.ProvisionRequestHandler.accept(ProvisionRequestHandler.java:19) [cloudbreak.jar!/:na]
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:74) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.invokeConsumer(ConsumerFilteringEventRouter.java:101) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:66) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.BaseDispatcher$Task.execute(BaseDispatcher.java:109) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at reactor.event.dispatch.ThreadPoolExecutorDispatcher$ThreadPoolTask.run(ThreadPoolExecutorDispatcher.java:108) [reactor-core-1.0.1.RELEASE.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:147) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:200) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.ParserRegistry.parseXML(ParserRegistry.java:267) ~[http-builder-0.7.1.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:952) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:411) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovy.lang.Closure.call(Closure.java:427) ~[groovy-all-2.1.8.jar!/:2.1.8]
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:560) ~[http-builder-0.7.1.jar!/:na]
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:489) ~[http-builder-0.7.1.jar!/:na]
	... 23 common frames omitted
2015-02-13 08:15:42,197 [thread-pool-executor-dispatcher-3] setupProvisioning:45 INFO  c.s.c.s.s.f.ProvisionSetupContext - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Publishing STACK_CREATE_FAILED event
2015-02-13 08:15:42,289 [thread-pool-executor-dispatcher-5] doUpdateStackStatus:231 INFO  c.s.c.r.RetryingStackUpdater - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Updated stack: [status: 'CREATE_FAILED', statusReason: 'Internal server error occured while setting up provisioning.'].
2015-02-13 08:15:42,290 [thread-pool-executor-dispatcher-5] fireCloudbreakEvent:49 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:cloudbreak] [type:EVENT_DATA] [id:50] [name:CREATE_FAILED] Fireing cloudbreak event: CloudbreakEventData{entityId=50, eventType='CREATE_FAILED', eventMessage='Internal server error occured while setting up provisioning.'}
2015-02-13 08:15:42,318 [thread-pool-executor-dispatcher-5] accept:75 INFO  c.s.c.s.s.h.StackCreationFailureHandler - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Accepted STACK_CREATE_FAILED event.
keyStorePath=file:///tmp/50.jks
2015-02-13 08:15:42,407 [thread-pool-executor-dispatcher-5] doUpdateStackStatusReason:244 INFO  c.s.c.r.RetryingStackUpdater - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:STACK] [id:50] [name:plupusandbox] Updated stack: [statusReason: 'Internal server error occured while setting up provisioning.'].
2015-02-13 08:15:42,408 [thread-pool-executor-dispatcher-5] fireCloudbreakEvent:49 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:cloudbreak] [type:EVENT_DATA] [id:50] [name:BILLING_STOPPED] Fireing cloudbreak event: CloudbreakEventData{entityId=50, eventType='BILLING_STOPPED', eventMessage='Stack creation failed.'}
2015-02-13 08:15:42,421 [thread-pool-executor-dispatcher-6] send:41 INFO  c.s.c.s.n.HttpNotificationSender - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Could not send notification to the specified endpoint: 'http://localhost:3000/notifications' Cause: I/O error on POST request for "http://localhost:3000/notifications":Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2015-02-13 08:15:42,422 [thread-pool-executor-dispatcher-6] createStackEvent:64 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:EVENT] [id:3] [name:CREATE_FAILED] Event and notification from the event were created: CloudbreakEvent{id=3, eventType='CREATE_FAILED', eventTimestamp=Fri Feb 13 08:15:42 UTC 2015, eventMessage='Internal server error occured while setting up provisioning.', owner='3ed3d788-ae78-4c68-a625-552701fa8b5c', account='abcd1234', cloud='AZURE', region='East US 2', vmType='MEDIUM', blueprintName='hdp-multinode-default', blueprintId=50, stackId=50}
2015-02-13 08:15:42,453 [thread-pool-executor-dispatcher-7] send:41 INFO  c.s.c.s.n.HttpNotificationSender - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Could not send notification to the specified endpoint: 'http://localhost:3000/notifications' Cause: I/O error on POST request for "http://localhost:3000/notifications":Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2015-02-13 08:15:42,453 [thread-pool-executor-dispatcher-7] createStackEvent:64 INFO  c.s.c.s.e.DefaultCloudbreakEventService - [owner:3ed3d788-ae78-4c68-a625-552701fa8b5c] [type:EVENT] [id:4] [name:BILLING_STOPPED] Event and notification from the event were created: CloudbreakEvent{id=4, eventType='BILLING_STOPPED', eventTimestamp=Fri Feb 13 08:15:42 UTC 2015, eventMessage='Stack creation failed.', owner='3ed3d788-ae78-4c68-a625-552701fa8b5c', account='abcd1234', cloud='AZURE', region='East US 2', vmType='MEDIUM', blueprintName='hdp-multinode-default', blueprintId=50, stackId=50}
2015-02-13 08:16:07,414 [taskScheduler-1] send:41 INFO  c.s.c.s.n.HttpNotificationSender - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Could not send notification to the specified endpoint: 'http://localhost:3000/notifications' Cause: I/O error on POST request for "http://localhost:3000/notifications":Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
2015-02-13 08:17:07,465 [taskScheduler-1] send:41 INFO  c.s.c.s.n.HttpNotificationSender - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Could not send notification to the specified endpoint: 'http://localhost:3000/notifications' Cause: I/O error on POST request for "http://localhost:3000/notifications":Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

**Comment by martonsereg** [comment]
Hi,

The current docker-cloudbreak container is deprecated but we’ll release a new version in a few days, so stay tuned, it will be available on our blog soon.

**Comment by paul-lupu** [comment]
So the current code is non-functional then?

**Comment by martonsereg** [comment]
It shouldn’t be completely non-functional, especially the AWS and GCP part. The Azure parts are considered unstable and the newer Cloudbreak version contains important fixes, but the docker container does not contain those changes yet.

**Comment by paul-lupu** [comment]
OK, so we'll wait for the next patch of the docker-cloudbreak container, are the connection refused errors also part of the patch?

owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Could not send notification to the specified endpoint: 'http://localhost:3000/notifications' Cause: I/O error on POST request for "http://localhost:3000/notifications":Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:3000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

**Comment by martonsereg** [comment]
I think yes, this is not a critical issue though - the UI websocket notifications won’t work if that error is present. It seems that the Cloudbreak container is trying to reach the UI container on localhost and that doesn’t work. With the new deployment we are using a different approach to connect containers so I guess this won’t be an issue anymore.

**Comment by paul-lupu** [comment]
After reading the documentation, there's one thing that is not very clear to me, in the case of a normal successful deploy, are the docker services placed inside docker containers within azure/ec2 hosts, or straight up into the virtual machines themselves?

**Comment by martonsereg** [comment]
Cloudbreak places all the Hadoop services inside docker containers, not on the VM directly. I suggest to check out our blog at http://blog.sequenceiq.com/ <http://blog.sequenceiq.com/>, we’ve shared a lot of technical details about our solutions there.
